<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    $cssCode .= <<<CSS

input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea,
a,
.mainmenu-container li a span,
.comment-metadata,
.comment-metadata a,
.c-body,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.comment-form label,
.comment-form a,
.widget .tagcloud a,
.widget.widget_tag_cloud a,
.cart-collaterals .cart_totals th,
#payment .payment_methods li.woocommerce-notice,
#payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods li.woocommerce-info,
table.woocommerce-checkout-review-order-table th,
.single-product .stock.out-of-stock,
.opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit span:before,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item.button-variable-item:not(.radio-variable-item):after,
.woocommerce-shipping-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.woocommerce-billing-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.opal-currency_switcher .list-currency button[type="submit"],
.select-items div {
  color: {$color_body}; }



b,
strong,
h1,
h2,
h3,
h4,
h5,
h6,
blockquote a,
.main-navigation .top-menu > li > a,
.post-content .posted-on a,
.more-link,
.entry-content blockquote cite a,
.entry-content strong,
.entry-content dt,
.entry-content dt a,
.entry-content th a,
body.single-post article.type-post .entry-title,
body.single-post .navigation .nav-link a,
.error404 .error-404-subtitle h2,
.error404 .error-text,
.comment-content strong,
.comment-author,
.comment-author a,
.comment-metadata a.comment-edit-link,
.comment-reply-link,
.comment-content table th,
.comment-content table td a,
.comment-content dt,
.widget a,
h2.widget-title,
h2.widgettitle,
.widget_rss .rss-date,
.widget_rss li cite,
.widget_recent_comments .recentcomments .comment-author-link,
.widget_search button[type="submit"],
.c-heading,
.form-group .form-row label,
fieldset legend,
.related-heading,
.comment-reply-title,
.comments-title,
.author-wrapper .author-name,
.page .entry-header .entry-title,
.site-header-account .login-form-title,
table.shop_table_responsive tbody th,
.site-header-cart .widget_shopping_cart p.total .woocommerce-Price-amount,
.site-header-cart .shopping_cart_nav p.total .woocommerce-Price-amount,
.filter-close,
table.cart:not(.wishlist_table) th,
.cart-collaterals .cart_totals .order-total .woocommerce-Price-amount,
.cart-collaterals .cart_totals .amount,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info,
#payment .payment_methods > .wc_payment_method > label,
table.woocommerce-checkout-review-order-table .order-total .woocommerce-Price-amount,
table.woocommerce-checkout-review-order-table .product-name,
.woocommerce-billing-fields label,
.woocommerce-billing-fields > h3,
.cart th,
.shop_table th,
.woocommerce-account .woocommerce-MyAccount-content strong,
.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Price-amount,
.osf-sorting .display-mode button.active,
.osf-sorting .display-mode button:hover,
.woocommerce-Tabs-panel table.shop_attributes th,
#osf-accordion-container table.shop_attributes th,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control],
.woosw-list table.woosw-content-items .woosw-content-item .woosw-content-item--add p > a,
.woosw-area .woosw-inner .woosw-content .woosw-content-mid table.woosw-content-items .woosw-content-item .woosw-content-item--add p > a,
.wishlist_table .product-price {
  color: {$color_heading}; }



.btn-link,
.button-link,
.breadcrumb,
.breadcrumb span,
.breadcrumb *,
.wpcf7 .wpcf7-form label span:first-child,
.mainmenu-container li.current-menu-parent > a,
.site-header .mainmenu-container .top-menu > li.current-menu-item > a,
.site-header .mainmenu-container .top-menu > li:hover > a,
.opal-pagination-6 .page-numbers.current:not(ul):not(.dots),
.opal-pagination-6 .page-numbers:not(ul):not(.dots):focus,
.opal-pagination-6 .page-numbers:not(ul):not(.dots):hover,
.site-header .header-group .search-submit:hover,
.site-header .header-group .search-submit:focus,
.header-search > a:hover,
.header-search > a:focus,
.post-content .posted-on a:hover,
.entry-meta a,
.cat-tags-links .tags-links a,
.pbr-social-share a:hover,
body.single-post .navigation > div:hover .thumbnail-nav,
body.single-post .navigation > div:hover a,
body.single-post .navigation > div:hover b,
body.single-post .navigation .next-nav:hover .thumbnail-nav,
body.single-post .navigation .next-nav:hover a,
.related-posts .related-heading:before,
.column-item .post-link a:hover,
.column-item.post-style-1 .post-inner a:hover,
.error404 .error-404 h1,
.error404 .error-text a,
.breadcrumb a:hover,
.breadcrumb a:hover span,
.site-header-account > a:hover,
.site-header-account > a:focus,
.comment-author a:hover,
.comment-metadata a:hover,
.opal-comment-4 .comment-reply-link,
.widget a:hover,
.widget a:focus,
.widget_recent_entries li a:hover,
.widget_recent_entries li a:active,
.widget_search button[type="submit"]:hover,
.widget_search button[type="submit"]:focus,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button,
.elementor-element .elementor-button-outline_primary button[type="submit"],
.c-primary,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.entry-title a:hover,
.entry-content blockquote cite a:hover,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.site-header-account .account-links-menu li a:hover,
.site-header-account .account-dashboard li a:hover,
.comment-form a:hover,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-nav-menu-popup .mfp-close,
.site-header-cart .widget_shopping_cart .product_list_widget li a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:focus,
.site-header-cart .shopping_cart_nav .product_list_widget li a:hover,
.site-header-cart .shopping_cart_nav .product_list_widget li a:focus,
.site-header-cart .woocommerce-mini-cart__empty-message:before,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a:hover,
.woocommerce-privacy-policy-link,
.opal-currency_switcher .list-currency button[type="submit"]:hover,
.opal-currency_switcher .list-currency li.active button[type="submit"],
ul.products li.product.osf-product-list .price,
ul.products li.product .posfed_in a:hover,
.select-items div:hover,
.single-product div.product .woocommerce-product-gallery .woocommerce-product-gallery__trigger:hover,
.button-wrapper #chart-button,
.product_list_widget a:hover,
.product_list_widget a:active,
.product_list_widget a:focus,
.woocommerce-product-list a:hover,
.woocommerce-product-list a:active,
.woocommerce-product-list a:focus,
.owl-theme.owl-carousel .owl-nav [class*='owl-']:hover:before,
.owl-theme .products .owl-nav [class*='owl-']:hover:before,
#secondary .elementor-widget-wp-widget-recent-posts a,
.contactform-content .form-title,
.elementor-widget-opal-product-categories .cats-title a:hover,
.elementor-widget-opal-testimonials .elementor-testimonial-wrapper .elementor-testimonial-name,
.elementor-widget-opal-testimonials .testimonial-control-prev:hover i,
.elementor-widget-opal-testimonials .testimonial-control-next:hover i,
.header-button .count,
.header-button:hover,
.header-button:focus,
.opal-canvas-filter .widget.widget_product_categories ul li a:hover,
.opal-canvas-filter .widget.widget_product_categories ul li.current-cat a,
.woocommerce-MyAccount-navigation ul li.is-active a,
.shop-action .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistaddedbrowse > a:before,
.shop-action .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistexistsbrowse a:before,
.single-product div.product .entry-summary .yith-wcwl-add-to-wishlist > div > a:hover,
.single-product div.product .entry-summary .compare:hover,
.single-product div.product form.cart .quantity input[type="button"]:hover,
.single-product div.product .pbr-social-share a:hover,
.widget_price_filter .price_slider_amount .price_label span,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item.button-variable-item:not(.radio-variable-item):hover,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item.button-variable-item.selected:not(.radio-variable-item),
.product-style-1 li.product h2 a:hover,
.product-style-1 li.product h3 a:hover,
.product-style-1 li.product .woocommerce-loop-product__title a:hover,
.product-style-1 li.product .shop-action .yith-wcqv-button:hover:before,
.product-style-1 li.product .shop-action .yith-wcwl-add-to-wishlist > div > a:hover:before,
.product-style-1 li.product .shop-action .compare:hover:before,
.product-style-2 li.product h2 a:hover,
.product-style-2 li.product h3 a:hover,
.product-style-2 li.product .woocommerce-loop-product__title a:hover,
.product-style-2 li.product .shop-action .woosc-btn:hover:before,
.product-style-2 li.product .shop-action .woosq-btn:hover:before,
.product-style-2 li.product .shop-action .woosw-btn:hover:before,
.product-style-2 li.product .shop-action .yith-wcqv-button:hover:before,
.product-style-2 li.product .shop-action .yith-wcwl-add-to-wishlist > div > a:hover:before,
.product-style-2 li.product .shop-action .compare:hover:before,
.product-style-2 li.product .posted_in a:hover,
.shop-action .woosc-btn:hover:before,
.shop-action .woosq-btn:hover:before,
.shop-action .woosw-btn:hover:before,
.single-product div.product .entry-summary .woosc-btn:hover,
.single-product div.product .entry-summary .woosw-btn:hover {
  color: {$color_primary->toCss()}; }


.f-primary {
  fill: {$color_primary->toCss()}; }


input[type="button"]:hover,
input[type="button"]:focus,
input[type="submit"]:hover,
input[type="submit"]:focus,
button[type="submit"]:hover,
button[type="submit"]:focus,
.page-numbers:not(ul):not(.dots):hover,
.page-numbers:not(ul):not(.dots):focus,
.page-numbers.current:not(ul):not(.dots),
.comments-link span,
.post-content .posted-on:after,
.post-thumbnail .posted-on,
.page-links a:hover .page-number,
.page-links a:focus .page-number,
.page-links > .page-number,
.search .site-content .site-main .search-form .search-submit:hover,
.wp_widget_tag_cloud a:hover:before,
.wp_widget_tag_cloud a:focus:before,
.related > h2:first-child:after,
.upsells > h2:first-child:after,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.elementor-element .elementor-button-primary .elementor-button,
.elementor-element .elementor-button-primary button[type="submit"],
.button-outline-primary:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.elementor-element .elementor-button-outline_primary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_primary button[type="submit"]:active,
.elementor-element .elementor-button-outline_primary button[type="submit"]:focus,
.bg-primary,
.owl-theme.owl-carousel .owl-dots .owl-dot,
.owl-theme .products .owl-dots .owl-dot,
.elementor-widget-divider .elementor-divider-separator:before,
.elementor-flip-box__front,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon-wrapper,
.elementor-widget-opal-product-categories .cats-title:before,
.property-variation-item .property_variation_button:hover,
.notification-added-to-cart .ns-content,
#payment .place-order .button:hover,
form.register .button[type="submit"]:hover,
li.product .time,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.single-product .single_add_to_cart_button:hover,
.single-product .single_add_to_cart_button.disabled[type="submit"]:hover,
.widget_price_filter .ui-slider .ui-slider-range,
.handheld-footer-bar .cart .footer-cart-contents .count {
  background-color: {$color_primary->toCss()}; }


.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-secondary,
.secondary-button .search-submit,
.form-control:focus,
textarea:focus,
input[type="button"]:hover,
input[type="button"]:focus,
input[type="submit"]:hover,
input[type="submit"]:focus,
button[type="submit"]:hover,
button[type="submit"]:focus,
.opal-pagination-3 .page-numbers.current:not(ul):not(.dots),
.opal-pagination-3 .page-numbers:not(ul):not(.dots):focus,
.opal-pagination-3 .page-numbers:not(ul):not(.dots):hover,
.opal-pagination-4 .page-numbers.current:not(ul):not(.dots),
.opal-pagination-4 .page-numbers:not(ul):not(.dots):focus,
.opal-pagination-4 .page-numbers:not(ul):not(.dots):hover,
.more-link:hover,
.column-item .post-link a:hover,
.search .site-content .site-main .search-form .search-submit:hover,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.wp_widget_tag_cloud a:hover:after,
.wp_widget_tag_cloud a:focus:after,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
.elementor-element .elementor-button-primary .elementor-button,
.elementor-element .elementor-button-primary button[type="submit"],
.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button,
.elementor-element .elementor-button-outline_primary button[type="submit"],
.button-outline-primary:hover,
.button-outline-primary:active,
.button-outline-primary.active,
.show > .button-outline-primary.dropdown-toggle,
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.elementor-element .elementor-button-outline_primary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_primary button[type="submit"]:active,
.elementor-element .elementor-button-outline_primary button[type="submit"]:focus,
.b-primary,
.elementor-widget-opal-testimonials .testimonial-control-prev:hover,
.elementor-widget-opal-testimonials .testimonial-control-next:hover,
#payment .place-order .button:hover,
form.register .button[type="submit"]:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.single-product .single_add_to_cart_button:hover,
.single-product .single_add_to_cart_button.disabled[type="submit"]:hover,
.osf-product-deal .woocommerce-product-list .opal-countdown .day,
.otf-product-recently-content li:hover .product-thumbnail img {
  border-color: {$color_primary->toCss()}; }


blockquote {
  border-left-color: {$color_primary->toCss()}; }



.btn-link:focus,
.btn-link:hover,
.button-link:focus,
.button-link:hover,
a:hover,
a:active,
.error404 .error-text a:hover {
  color: {$color_primary_hover->toCss()}; }


.post-thumbnail .posted-on:hover,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.elementor-element .elementor-button-primary button[type="submit"]:hover,
.elementor-element .elementor-button-primary button[type="submit"]:active,
.elementor-element .elementor-button-primary button[type="submit"]:focus {
  background-color: {$color_primary_hover->toCss()}; }


.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.elementor-element .elementor-button-primary button[type="submit"]:hover,
.elementor-element .elementor-button-primary button[type="submit"]:active,
.elementor-element .elementor-button-primary button[type="submit"]:focus {
  border-color: {$color_primary_hover->toCss()}; }




.button-outline-secondary,
.elementor-element .elementor-button-outline_secondary .elementor-button,
.elementor-element .elementor-button-outline_secondary button[type="submit"],
.c-secondary,
.author-wrapper .author-name h6,
.contactform-content button.mfp-close,
.property-variation-item .property_variation_button,
.opal-property-variation {
  color: {$color_secondary->toCss()}; }



.button-secondary,
.secondary-button .search-submit,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.elementor-element .elementor-button-secondary button[type="submit"],
.button-outline-secondary:hover,
.button-outline-secondary:active,
.button-outline-secondary.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:active,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:focus,
.bg-secondary,
#secondary .elementor-widget-wp-widget-categories a:before,
.elementor-flip-box__back,
#secondary .elementor-nav-menu a:before,
.e--pointer-dot a:before {
  background-color: {$color_secondary->toCss()}; }



.button-secondary,
.secondary-button .search-submit,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.elementor-element .elementor-button-secondary button[type="submit"],
.button-outline-secondary,
.elementor-element .elementor-button-outline_secondary .elementor-button,
.elementor-element .elementor-button-outline_secondary button[type="submit"],
.button-outline-secondary:hover,
.button-outline-secondary:active,
.button-outline-secondary.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:active,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:focus,
.b-secondary {
  border-color: {$color_secondary->toCss()}; }



.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus,
.elementor-element .elementor-button-secondary button[type="submit"]:hover,
.elementor-element .elementor-button-secondary button[type="submit"]:active,
.elementor-element .elementor-button-secondary button[type="submit"]:focus {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus,
.elementor-element .elementor-button-secondary button[type="submit"]:hover,
.elementor-element .elementor-button-secondary button[type="submit"]:active,
.elementor-element .elementor-button-secondary button[type="submit"]:focus {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.opal-archive-style-4.blog .site-main,
.opal-archive-style-4.archive .site-main,
.opal-default-content-layout-2cr .site-content .wrap,
.site-footer .widget-area,
.opal-comment-form-2 .comment-form,
.opal-comment-form-3 .comment-form,
.opal-comment-form-4 .comment-form,
.opal-comment-form-6 .comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
[data-elementor-columns],
.opal-canvas-filter.top .opal-canvas-filter-wrap,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone,
.woocommerce-cart .woocommerce,
.woocommerce-billing-fields .woocommerce-billing-fields__field-wrapper,
.woocommerce-MyAccount-content form[class^="woocommerce-"],
.woocommerce-columns--addresses,
form.track_order,
.woocommerce-account .woocommerce,
.woocommerce-Addresses,
.woocommerce-address-fields__field-wrapper,
ul.products,
.osf-sorting,
.single-product div.product,
.single-product div.product .woocommerce-product-gallery .flex-control-thumbs {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.col-4,
.opal-comment-form-2 .comment-form .comment-form-author,
.opal-comment-form-3 .comment-form .comment-form-author,
.opal-comment-form-2 .comment-form .comment-form-email,
.opal-comment-form-3 .comment-form .comment-form-email,
.opal-comment-form-2 .comment-form .comment-form-url,
.opal-comment-form-3 .comment-form .comment-form-url,
[data-elementor-columns-mobile="3"] .column-item,
.col-5,
.col-6,
.opal-comment-form-4 .comment-form .comment-form-author,
.opal-comment-form-4 .comment-form .comment-form-email,
.opal-comment-form-4 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .comment-form-author,
.opal-comment-form-6 .comment-form .comment-form-email,
[data-elementor-columns-mobile="2"] .column-item,
.single-product.opal-comment-form-2 .comment-form-author,
.single-product.opal-comment-form-3 .comment-form-author,
.single-product.opal-comment-form-2 .comment-form-email,
.single-product.opal-comment-form-3 .comment-form-email,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.opal-archive-style-2.opal-content-layout-2cr .post-style-2,
.related-posts .column-item,
.opal-default-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
.site-footer .widget-area .widget-column,
.opal-comment-form-2 .comment-form .logged-in-as,
.opal-comment-form-3 .comment-form .logged-in-as,
.opal-comment-form-2 .comment-form .comment-notes,
.opal-comment-form-3 .comment-form .comment-notes,
.opal-comment-form-2 .comment-form .comment-form-comment,
.opal-comment-form-3 .comment-form .comment-form-comment,
.opal-comment-form-2 .comment-form .form-submit,
.opal-comment-form-3 .comment-form .form-submit,
.opal-comment-form-4 .comment-form .logged-in-as,
.opal-comment-form-4 .comment-form .comment-notes,
.opal-comment-form-4 .comment-form .comment-form-comment,
.opal-comment-form-4 .comment-form .form-submit,
.opal-comment-form-6 .comment-form .logged-in-as,
.opal-comment-form-6 .comment-form .comment-notes,
.opal-comment-form-6 .comment-form .comment-form-comment,
.opal-comment-form-6 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .form-submit,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.woocommerce-cart .cart-empty,
.woocommerce-cart .return-to-shop,
.woocommerce-billing-fields .form-row-wide,
.woocommerce-MyAccount-content form[class^="woocommerce-"] > *:not(fieldset),
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-wide,
#customer_details [class*='col'],
.woocommerce-Addresses .woocommerce-Address,
.columns-1 ul.products li.product,
.columns-1 ul.products > li,
#reviews .comment-form-rating,
.col,
body #secondary,
.opal-canvas-filter.top .opal-canvas-filter-wrap section,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone .woof_container,
form.track_order p.form-row-first,
form.track_order p.form-row-last,
.columns-5 ul.products li.product,
.columns-5 ul.products > li,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.columns-6 ul.products li.product,
.columns-6 ul.products > li,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.opal-archive-style-3:not(.opal-content-layout-2cr) .post-style-3,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.woocommerce-billing-fields .form-row-first,
.woocommerce-billing-fields .form-row-last,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-first,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-last,
ul.products li.product,
.columns-2 ul.products li.product,
.columns-2 ul.products > li,
.columns-3 ul.products li.product,
.columns-3 ul.products > li,
.columns-4 ul.products li.product,
.columns-4 ul.products > li,
.opal-content-layout-2cl .columns-3 ul.products li.product,
.opal-content-layout-2cl .columns-3 ul.products > li,
.opal-content-layout-2cr .columns-3 ul.products li.product,
.opal-content-layout-2cr .columns-3 ul.products > li,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.opal-archive-style-2:not(.opal-content-layout-2cr) .post-style-2,
.opal-archive-style-3.opal-content-layout-2cr .post-style-3,
.cart-collaterals .cross-sells,
.woocommerce-columns--addresses .woocommerce-column,
.woocommerce-account .woocommerce-MyAccount-navigation,
.woocommerce-account .woocommerce-MyAccount-content,
.woocommerce-address-fields__field-wrapper .form-row,
.woocommerce-product-carousel ul.products li.product,
.osf-sorting .woocommerce-message,
.osf-sorting .woocommerce-notice,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group,
.single-product div.product .entry-summary,
.single-product div.product .images,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.col-md-4,
[data-elementor-columns-tablet="3"] .column-item,
.col-md-5,
.opal-default-content-layout-2cr #secondary,
.osf-sorting .osf-sorting-group,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.col-md-7,
.opal-default-content-layout-2cr #primary,
.osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
[data-elementor-columns="6"] .column-item,
.col-lg-3,
[data-elementor-columns="4"] .column-item,
.col-lg-4,
[data-elementor-columns="3"] .column-item,
.col-lg-5,
.col-lg-6,
[data-elementor-columns="2"] .column-item,
.col-lg-7,
.col-lg-8,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group + .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
[data-elementor-columns="1"] .column-item,
.cart-collaterals,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
.opal-canvas-filter.top,
.single-product .related.products,
.single-product .up-sells.products,
.otf-product-recently-content .widget_recently_viewed_products {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 1140px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $border_radius, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS

.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.elementor-element .elementor-button-primary .elementor-button,
.elementor-element .elementor-button-primary button[type="submit"] {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.elementor-element .elementor-button-primary button[type="submit"]:hover,
.elementor-element .elementor-button-primary button[type="submit"]:active,
.elementor-element .elementor-button-primary button[type="submit"]:focus {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
    {$font_style_code}
}




.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button,
.elementor-element .elementor-button-outline_primary button[type="submit"] {
    color: {$primary_color_outline};
    border-color: {$primary_border};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-outline-primary:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.elementor-element .elementor-button-outline_primary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_primary button[type="submit"]:active,
.elementor-element .elementor-button-outline_primary button[type="submit"]:focus {
    color: {$primary_color_hover};
    background-color: {$primary_hover};
    border-color: {$primary_border_hover};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $border_radius, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-secondary,
.secondary-button .search-submit,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.elementor-element .elementor-button-secondary button[type="submit"] {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.secondary-button .search-submit:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus,
.elementor-element .elementor-button-secondary button[type="submit"]:hover,
.elementor-element .elementor-button-secondary button[type="submit"]:active,
.elementor-element .elementor-button-secondary button[type="submit"]:focus {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}




.button-outline-secondary,
.elementor-element .elementor-button-outline_secondary .elementor-button,
.elementor-element .elementor-button-outline_secondary button[type="submit"] {
    color: {$secondary_color_outline};
    border-color: {$secondary_border};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-outline-secondary:hover,
.button-outline-secondary:active,
.button-outline-secondary.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:hover,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:active,
.elementor-element .elementor-button-outline_secondary button[type="submit"]:focus {
    color: {$secondary_color_hover};
    background-color: {$secondary_hover};
    border-color: {$secondary_border_hover};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-secondary,
.secondary-button .search-submit,
.button-outline-primary,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-outline-secondary,
h1,
h2,
h3,
h4,
h5,
h6,
.site-header .mainmenu-container .top-menu > li > a,
.opal-pagination-6 .page-numbers:not(ul):not(.dots),
.more-link,
.pbr-social-share .social-share-header,
body.single-post article.type-post .entry-footer .tags-title,
body.single-post .navigation .nav-content,
.author-wrapper .author-name,
.column-item .post-link a,
.error404 .error-404 h1,
.error404 .error-404-subtitle h2,
h2.widget-title,
h2.widgettitle,
.widget_recent_entries li.item-recent-post a,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-element .elementor-button,
.contactform-content .form-title,
.opal-image-hotspots-tooltips-product .product-price,
.elementor-widget-opal-product-categories .cats-title a,
.filter-toggle,
form.track_order label,
li.product .onsale,
ul.products li.product .price,
.single-product div.product .summary .price,
.single-product div.product table.variations label,
.single-product div.product .product_meta .sku_wrapper,
.single-product div.product .product_meta .posted_in,
.single-product div.product .product_meta .tagged_as,
.single-product div.product .pbr-social-share a,
.woocommerce-tabs ul.tabs li a,
.osf-product-deal .woocommerce-product-list .opal-countdown,
.product-style-1 li.product a[class*="product_type_"],
.product-style-2 li.product a[class*="product_type_"] {
    {$heading_css}
}


CSS;
    return $cssCode;
}
